export const SET_NAME = "SET_NAME";
export const SET_SINGLE_CHOICE = "SET_SINGLE_CHOICE";
export const SET_DROPDOWN_INPUT = "SET_DROPDOWN_INPUT";
export const SET_MULTIPLE_CHOICES = "SET_MULTIPLE_CHOICES";
export const REMOVE_MULTIPLE_CHOICE = "REMOVE_MULTIPLE_CHOICE";
